-- MySQL Script generated by MySQL Workbench
-- Mon Oct 18 14:06:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema task_force
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `task_force` ;

-- -----------------------------------------------------
-- Schema task_force
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `task_force` DEFAULT CHARACTER SET utf8 ;
USE `task_force` ;

-- -----------------------------------------------------
-- Table `task_force`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`category` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `name` VARCHAR(45) NOT NULL COMMENT 'Название',
  `icon` VARCHAR(45) NOT NULL COMMENT 'Иконка',
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `task_force`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`city` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `name` VARCHAR(45) NOT NULL COMMENT 'Название',
  `lat` DECIMAL(10,8) NOT NULL COMMENT 'Широта',
  `lng` DECIMAL(11,8) NOT NULL COMMENT 'Долгота',
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `task_force`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `role` VARCHAR(20) NOT NULL COMMENT 'Роль',
  `email` VARCHAR(255) NOT NULL COMMENT 'Электронная почта',
  `password_hash` VARCHAR(255) NOT NULL COMMENT 'Хэш пароля',
  `name` VARCHAR(60) NOT NULL COMMENT 'Ваше имя',
  `birth_date` DATE NULL DEFAULT NULL COMMENT 'Дата рождения',
  `description` TEXT NULL DEFAULT NULL COMMENT 'Информация о себе',
  `city_id` INT(10) UNSIGNED NOT NULL COMMENT 'Город',
  `avatar` VARCHAR(15) NULL DEFAULT NULL COMMENT 'Аватар',
  `photos` JSON NULL DEFAULT NULL COMMENT 'Фото работ',
  `phone` VARCHAR(11) NULL DEFAULT NULL COMMENT 'Телефон',
  `skype` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Skype',
  `telegram` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Телеграм',
  `hidden` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Не показывать мой профиль',
  `show_contacts_only_for_customer` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Показывать мои контакты только заказчику',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Дата регистрации',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT 'Дата обновления',
  `last_action_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Время последннего действия',
  `new_message_notice` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Новое сообщение',
  `task_action_notice` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Действия по заданию',
  `new_opinion_notice` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Новый отзыв',
  PRIMARY KEY (`id`),
  INDEX `fk_user_city_idx` (`city_id` ASC),
  CONSTRAINT `fk_user_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `task_force`.`city` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `task_force`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`task` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `status` VARCHAR(20) NOT NULL,
  `title` VARCHAR(255) NOT NULL COMMENT 'Мне нужно',
  `description` TEXT NOT NULL COMMENT 'Подробности задания',
  `category_id` INT(10) UNSIGNED NOT NULL COMMENT 'Категория',
  `customer_id` INT(10) UNSIGNED NOT NULL COMMENT 'Заказчик',
  `executor_id` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Исполнитель',
  `files` JSON NULL DEFAULT NULL COMMENT 'Файлы',
  `lat` DECIMAL(10,8) NULL DEFAULT NULL COMMENT 'Широта',
  `lng` DECIMAL(11,8) NULL DEFAULT NULL COMMENT 'Долгота',
  `city_id` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Локация',
  `budget` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Бюджет',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Дата создания',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT 'Дата обновления',
  `expired_at` DATE NULL DEFAULT NULL COMMENT 'Срок исполнения',
  PRIMARY KEY (`id`),
  INDEX `fk_task_category_idx` (`category_id` ASC),
  INDEX `fk_task_city_idx` (`city_id` ASC),
  INDEX `fk_task_customer_idx` (`customer_id` ASC),
  INDEX `fk_task_executor_idx` (`executor_id` ASC),
  CONSTRAINT `fk_task_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `task_force`.`category` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_task_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `task_force`.`city` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_task_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `task_force`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_task_executor`
    FOREIGN KEY (`executor_id`)
    REFERENCES `task_force`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `task_force`.`response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`response` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `user_id` INT(10) UNSIGNED NOT NULL COMMENT 'Исполнитель',
  `task_id` INT(10) UNSIGNED NOT NULL COMMENT 'Задание',
  `budget` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Ваша цена',
  `text` TEXT NULL DEFAULT NULL COMMENT 'Комментарий',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Дата регистрации',
  `rejected` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Отклонён',
  PRIMARY KEY (`id`),
  INDEX `fk_response_user_idx` (`user_id` ASC),
  INDEX `fk_response_task_idx` (`task_id` ASC),
  CONSTRAINT `fk_response_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `task_force`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_response_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `task_force`.`task` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `task_force`.`opinion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`opinion` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `task_id` INT(10) UNSIGNED NOT NULL COMMENT 'Задание',
  `grade` TINYINT(1) UNSIGNED NOT NULL COMMENT 'Оценка',
  `text` TEXT NOT NULL COMMENT 'Комментарий',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Дата создания',
  PRIMARY KEY (`id`),
  INDEX `fk_opinion_task_idx` (`task_id` ASC),
  CONSTRAINT `fk_opinion_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `task_force`.`task` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `task_force`.`user_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`user_category` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `user_id` INT(10) UNSIGNED NOT NULL COMMENT 'Пользователь',
  `category_id` INT(10) UNSIGNED NOT NULL COMMENT 'Категория',
  PRIMARY KEY (`id`),
  INDEX `fk_user_category_category_idx` (`category_id` ASC),
  INDEX `fk_user_category_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_category_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `task_force`.`category` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_category_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `task_force`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `task_force`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_force`.`message` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `user_id` INT(10) UNSIGNED NOT NULL COMMENT 'Пользователь',
  `task_id` INT(10) UNSIGNED NOT NULL COMMENT 'Задание',
  `text` TEXT NOT NULL COMMENT 'Сообщение',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Дата создания',
  `unread` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Непрочитанно',
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user_idx` (`user_id` ASC),
  INDEX `fk_comment_task_idx` (`task_id` ASC),
  CONSTRAINT `fk_comment_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `task_force`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `task_force`.`task` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
